### ISSUE TITLE
Consider removing Node built-in modules polyfills

### ISSUE THREAD

**Issue by ShGKme** [nextcloud-libraries/webpack-vue-config#450]
## Preface

In the past Webpack polyfilled built-in Node.js modules. It was changed in Webpack 5. But some modules require built-in Node module polyfills. To fix that currently the `node-polyfill-webpack-plugin` is used, which returns Webpack 4 behavior.

## The problem

Many Node polyfills are useless. (For example, `console` and `Buffer` are available in Web Browsers). But they still increase the bundle size and bundling time.

For example, for the Talk frontend, it adds about **189kb** raw in the production build. It may sound small but:
* JS size is more than just bytes, more than the image size. It has to be parsed, compiled, and evaluated.
* This is just one app. If a server instance has 10 different apps installed, then it could be 10 times more.

## ⚠️ BREAKING CHANGE

This would be a breaking change. Any app building may break if it requires any polyfill.

To decrease the number of breaks we may provide fallback with polyfills, required by Nextcloud libs, by default: `stream` and `path`. For most app it might be enough. 

```js
resolve: {
  fallback: {
    stream: require.resolve('stream-browserify'),
    path: require.resolve('path-browserify'),
  },
}
```

## Why do not change anything here

Nextcloud Server + apps frontend is very large, and this small change may seem like a drop in the sea. But on the other hand, it is small and simple change (with a small breaking change).

**Comment by juliushaertl** [comment]
@ShGKme  If Buffer really available? I noticed that with the latest `@nextcloud/files` i needed to add buffer and path to the `resolve.fallback` config to make this work in text: https://github.com/nextcloud/text/pull/4630/commits/6935fa6ea79d41ce60bc7efbeafd491e91b9f0a8

**Comment by skjnldsv** [comment]
> @ShGKme If Buffer really available? I noticed that with the latest `@nextcloud/files` i needed to add buffer and path to the `resolve.fallback` config to make this work in text: [nextcloud/text@6935fa6](https://github.com/nextcloud/text/commit/6935fa6ea79d41ce60bc7efbeafd491e91b9f0a8)

I had to do this to Text yesterday yes

**Comment by susnux** [comment]
Buffer is not available. Well it is but its API is different from the Node.js Buffer API.

Both share some API, but some parts do not behave the same, so basically you can not be sure 3rd party libraries only use API which works on browser and Node. Thats why you probably need to polyfill every node module (except `console`).

**Comment by ShGKme** [comment]
Fixed by https://github.com/nextcloud-libraries/webpack-vue-config/pull/449
